name: Build and Release

on:
  release:
    types: [created, published]
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    # Allows manual triggering of this workflow

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            script: npm run pack-linux
          - os: windows-latest
            script: npm run pack-win
          - os: macos-latest
            script: npm run pack-mac

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build for ${{ matrix.os }}
        run: ${{ matrix.script }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}
          path: |
            dist/*.dmg
            dist/*.AppImage
            dist/*.deb
            dist/*.exe
            dist/*.zip 